trigger:
- release

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_ElMoufid-Mohamed'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'v$(Build.BuildNumber)'
    title: 'v$(Build.BuildNumber)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd 'Web Application'
    cd 'MM-Crypto'
    npm install -g @angular/cli
    npm install -g firebase-tools
    npm install
    ng build --prod
    firebase deploy --token $(firebase-token) --project $(project-id) --message "Azure DevOps"
  displayName: 'npm install and build and deploy'